var wordleData = {
	dictionary: [
		{ word: "CHAT", hint: "Conversation" },
		{ word: "FIRE", hint: "Combustion" },
		{ word: "GOLD", hint: "Precious metal" },
		{ word: "LAMP", hint: "Light source" },
		{ word: "FROG", hint: "Amphibian" },
		{ word: "KITE", hint: "Flying toy" },
		{ word: "LAZY", hint: "Lacking motivation" },
		{ word: "ROSE", hint: "Flower" },
		{ word: "TIME", hint: "Clock measurement" },
		{ word: "WINE", hint: "Alcoholic beverage" },
		{ word: "BLUE", hint: "Color" },
		{ word: "MATH", hint: "Subject with numbers" },
		{ word: "DOOR", hint: "Entrance barrier" },
		{ word: "TREE", hint: "Tall plant" },
		{ word: "RAIN", hint: "Water falling from the sky" },
		{ word: "KISS", hint: "Affectionate gesture" },
		{ word: "JUMP", hint: "Leap in the air" },
		{ word: "CODE", hint: "Programming instructions" },
		{ word: "SOUP", hint: "Liquid food" },
		{ word: "SNOW", hint: "Frozen precipitation" },
		{ word: "GIFT", hint: "Present" },
		{ word: "BIRD", hint: "Feathered creature" },
		{ word: "LOCK", hint: "Securing mechanism" },
		{ word: "MOON", hint: "Celestial body" },
		{ word: "WALK", hint: "Stroll" },
		{ word: "PINK", hint: "Color" },
		{ word: "CAKE", hint: "Sweet dessert" },
		{ word: "RICE", hint: "Grain staple" },
		{ word: "FISH", hint: "Aquatic creature" },
		{ word: "COLD", hint: "Low temperature" },
		{ word: "LION", hint: "Wild cat" },
		{ word: "SING", hint: "Make music with the voice" },
		{ word: "LOUD", hint: "High volume" },
		{ word: "EYES", hint: "Sight organs" },
		{ word: "BEAR", hint: "Large mammal" },
		{ word: "FLOW", hint: "Movement of a liquid" },
		{ word: "TALL", hint: "High in height" },
		{ word: "HAIR", hint: "Head covering" },
		{ word: "CUTE", hint: "Adorable" },
		{ word: "HOTEL", hint: "Accommodation place" },
		{ word: "JUMP", hint: "Leap in the air" },
		{ word: "LAKE", hint: "Body of water" },
		{ word: "SOFT", hint: "Gentle to the touch" },
		{ word: "PLAY", hint: "Engage in recreation" },
		{ word: "LIME", hint: "Citrus fruit" },
		{ word: "SALT", hint: "Seasoning" },
		{ word: "FACE", hint: "Facial features" },
	],
};
